### ISSUE TITLE
#24 make final improvements

### ISSUE THREAD

**Issue by dfilipuk** [AlexKozlovsci/red-dragon-news#28]

**Comment by AlexKozlovsci** [comment]
#3 add picture on tab

**Comment by AlexKozlovsci** [comment]
#4 fixate footer to bottom

**Comment by Kupilif** [comment]
#5 add symfony translations

**Comment by AlexKozlovsci** [comment]
#6 add ajax for category tree output

**Comment by AlexKozlovsci** [comment]
#7 add styles for all categories page

**Comment by Kupilif** [comment]
#8 change text on pagination labels

**Comment by AlexKozlovsci** [comment]
change input color in edit

**Comment by AlexKozlovsci** [comment]
#9 not delete user when exist token in tokens base

**Comment by AlexKozlovsci** [comment]
№10 problem woth categories tree

**Comment by AlexKozlovsci** [comment]
#11 similar news

**Comment by AlexKozlovsci** [comment]
#12 change category select

**Comment by AlexKozlovsci** [comment]
fix empty article text bug

**Comment by Kupilif** [comment]
MAIN: fix db error when try to insert article with empty text

**Comment by dfilipuk** [comment]
check code for PSR standart

**Comment by Kupilif** [comment]
change article creation time output format

**Comment by AlexKozlovsci** [comment]
add typehints
